# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestRegistrations():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_registrations(self):
        self.driver.get("https://pentesttools.co.uk//")
        self.driver.find_element(By.CSS_SELECTOR,
                                 "ul > .page-item-61 > a").click()
        self.driver.find_element(By.CSS_SELECTOR, ".entry-header").click()
        self.driver.find_element(By.CSS_SELECTOR, ".entry-content").click()
        self.driver.find_element(By.ID, "reg-username").click()
        self.driver.find_element(By.ID, "reg-username").send_keys("test1")
        self.driver.find_element(By.ID, "reg-password").send_keys("anotherst")
        self.driver.find_element(By.ID, "reg-email").send_keys("testpw@ee.com")
        self.driver.find_element(By.ID, "reg-website").send_keys("none.com")
        self.driver.find_element(By.ID, "id-nickname").send_keys("test11")
        self.driver.find_element(By.ID, "reg-firstname").send_keys("t1")
        self.driver.find_element(By.ID, "reg-lastname").send_keys("user")
        self.driver.find_element(By.ID, "submit-button").click()
