# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestLogin():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://pentesttools.co.uk/")
        self.driver.find_element(By.CSS_SELECTOR, ".home").click()
        self.driver.find_element(By.LINK_TEXT, "Log In").click()
        self.driver.find_element(By.ID, "login-name").click()
        self.driver.find_element(By.ID, "login-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".entry-content").click()
        self.driver.find_element(By.ID, "login-name").click()
        self.driver.find_element(By.CSS_SELECTOR, ".entry-header").click()
        self.driver.find_element(By.ID, "login-pass").click()
        self.driver.find_element(By.NAME, "login_submit").click()
