# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://pentesttools.co.uk/")
    self.driver.find_element(By.CSS_SELECTOR, ".home").click()
    self.driver.find_element(By.LINK_TEXT, "Log In").click()
    self.driver.find_element(By.ID, "login-name").click()
    self.driver.find_element(By.ID, "login-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".entry-content").click()
    self.driver.find_element(By.ID, "login-name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".entry-header").click()
    self.driver.find_element(By.ID, "login-pass").click()
    self.driver.find_element(By.NAME, "login_submit").click()
  
